package com.hrmsrevamp.constants;
/**
 * UserAuditActivity Enum.
 */
public enum UserAuditActivityEnum {

  USER_SIGNED_UP_SUCCESSFULLY,
  LAST_LOGGED_IN,
  DEVICE_ADDED,
  DEVICE_UPDATED,
  DEVICE_STATUS_UPDATED,
  DEVICE_DELETED,
  USER_RESET_PASSWORD_DONE,
  USER_TRIED_TO_ADD_MORE_THAN_10_DEVICES,
  USER_PROFILE_DELETED,
  USER_PROFILE_UPDATED,
  USER_SIGNED_IN_SUCCESSFULLY,
  USER_SIGNED_OUT_SUCCESSFULLY,
  USER_STATUS_UPDATED_SUCCESSFULLY,
  DEVICE_QUOTA_LIMIT_REACHED,
  PLAN_SELECTED_BY_USER,
  USER_PLAN_UPGRADED,
  USER_PASSWORD_CHANGED,
  USER_PROFILE_DELETED_REASON,
  USER_ROLE_UPDATED_SUCCESSFULLY,
  SUBSCRIPTION_PLAN_CANCELED;
}
